# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true # deprecated

# Setup
title:            Dev Blog
tagline:          'Another developer blog'
description:      'Another developer blog where I might try and post'
url:              https://crr0004.github.com
baseurl:          /

author:
  name:           'Chris R'
  url:            https://twitter.com/crr0004
social:
    twitter: https://twitter.com/crr0004
    github: https://github.com/crr0004
    linkedin: https://linkedin.com/in/rhodeschristopher


paginate:         5

# Custom vars
version:          2.1.0
