# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Dev Blog
tagline:          'Developer blog by Christopher'
description:      'Developer blog by Christopher'
url:              https://crr0004.github.com
baseurl:          ''

author:
  name:           'Chris R'
  url:            https://twitter.com/crr0004

social:
    twitter: 
      link: https://twitter.com/crr0004
      icon: twitter.svg
    github: 
      link: https://github.com/crr0004
      icon: github.svg
    linkedin: 
      link: https://linkedin.com/in/rhodeschristopher
      icon: linkedin.svg
    devto: 
      link: https://dev.to/crr0004
      icon: devto.svg

plugins:
  - jekyll-gist
  - jekyll-paginate

# site wide comments disable
comments : false

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
# Custom vars
version:            3.7.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
