# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true # deprecated

# Setup
title:            Dev Blog
tagline:          'Another developer blog'
description:      'Another developer blog where I might try and post'
url:              http://crr0004.github.com
baseurl:          /

author:
  name:           'Chris R'
  url:            https://twitter.com/crr0004
social:
    twitter: http://twitter.com/crr0004
    github: http://github.com/crr0004
    linkedin: http://linkedin.com/in/rhodeschristopher


paginate:         5

# Custom vars
version:          2.1.0
