# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Dev Blog
tagline:          'Another developer blog'
description:      'Another developer blog where I ramble'
url:              https://crr0004.github.com
baseurl:          ''

author:
  name:           'Chris R'
  url:            https://twitter.com/crr0004
social:
    twitter: https://twitter.com/crr0004
    github: https://github.com/crr0004
    linkedin: https://linkedin.com/in/rhodeschristopher

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
# Custom vars
version:            3.7.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

# Custom vars
version:          2.1.0
